#!/bin/sh

#
# Use these scripts to (test and) deploy the octodns config in this repository.
#
# - script/test: Test this version of the configuration.
#

# Change directory to the root of this repository.
cd "$(git rev-parse --show-toplevel)" || return

# Set environment variables.
. ./.config

# - Lint all the things.
./test/00_linters

# - Test our Dockerfile.
./test/10_test-build Dockerfile
